/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiaregistro;

import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rodri
 */
public class Registros extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
        super.setTitle("Registro");
        super.setLocationRelativeTo(null);
        super.setResizable(false);
        tfCum.setEditable(false);
        tfDescripcion.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbCarrera = new javax.swing.JComboBox<>();
        rbCiclo01 = new javax.swing.JRadioButton();
        rbCiclo02 = new javax.swing.JRadioButton();
        btnRegistrarse = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        lbTituloVentana = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbCiclo = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        lbImg = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        lbUv = new javax.swing.JLabel();
        cbUv1 = new javax.swing.JComboBox<>();
        cbUv2 = new javax.swing.JComboBox<>();
        cbUv3 = new javax.swing.JComboBox<>();
        cbUv4 = new javax.swing.JComboBox<>();
        cbUv5 = new javax.swing.JComboBox<>();
        lbEstado1 = new javax.swing.JLabel();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado3 = new javax.swing.JLabel();
        lbEstado4 = new javax.swing.JLabel();
        lbEstado5 = new javax.swing.JLabel();
        lbCum = new javax.swing.JLabel();
        tfCum = new javax.swing.JTextField();
        lbNotas = new javax.swing.JLabel();
        tfNota1 = new javax.swing.JTextField();
        tfNota2 = new javax.swing.JTextField();
        tfNota3 = new javax.swing.JTextField();
        tfNota5 = new javax.swing.JTextField();
        tfNota4 = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione las carreras", "Ingenieria en Sistemas", "Ingenieria Industrial", "Ingenieria en Agronegocios", "Ingenieria Electrica" }));

        buttonGroup1.add(rbCiclo01);
        rbCiclo01.setText("Ciclo 01");

        buttonGroup1.add(rbCiclo02);
        rbCiclo02.setText("Ciclo 02");
        rbCiclo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCiclo02ActionPerformed(evt);
            }
        });

        btnRegistrarse.setBackground(new java.awt.Color(51, 153, 0));
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrar");
        btnRegistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(0, 51, 255));
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbTituloVentana.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lbTituloVentana.setForeground(new java.awt.Color(0, 0, 0));
        lbTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloVentana.setText("REGISTROS");
        lbTituloVentana.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbNombre.setText("Nombre:");

        lbApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbApellido.setText("Apellido:");

        lbCorreo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbCorreo.setText("Correo:");

        lbCarrera.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbCarrera.setText("Carrera:");

        lbCiclo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbCiclo.setText("Ciclo Actual:");

        tfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoActionPerformed(evt);
            }
        });

        lbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaregistro/UsoImg.png"))); // NOI18N

        lbMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbMateria.setText("Materia");

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Desarrollo de Software", "Bases de Datos II", "Electronica", "Investigacion Operaciones", "Legislacion" }));
        cbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria1ActionPerformed(evt);
            }
        });

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Desarrollo de Software", "Bases de Datos II", "Electronica", "Investigacion Operaciones", "Legislacion" }));

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Desarrollo de Software", "Bases de Datos II", "Electronica", "Investigacion Operaciones", "Legislacion" }));
        cbMateria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria4ActionPerformed(evt);
            }
        });

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Desarrollo de Software", "Bases de Datos II", "Electronica", "Investigacion Operaciones", "Legislacion" }));
        cbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria3ActionPerformed(evt);
            }
        });

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Desarrollo de Software", "Bases de Datos II", "Electronica", "Investigacion Operaciones", "Legislacion" }));

        lbUv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbUv.setText("UV");

        cbUv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));

        cbUv2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));

        cbUv3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));

        cbUv4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));

        cbUv5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "3", "4" }));

        lbEstado1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbEstado1.setText("ESTADO");

        lbEstado2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbEstado2.setText("ESTADO");

        lbEstado3.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbEstado3.setText("ESTADO");

        lbEstado4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbEstado4.setText("ESTADO");

        lbEstado5.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbEstado5.setText("ESTADO");

        lbCum.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbCum.setText("CUM");

        tfCum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCumActionPerformed(evt);
            }
        });

        lbNotas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbNotas.setText("Notas");

        tfNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbImg)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbMateria1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMateria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMateria3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMateria4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lbMateria)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbUv)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lbNotas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCum)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNota5)
                                    .addComponent(tfNota4)
                                    .addComponent(tfNota3)
                                    .addComponent(tfNota2)
                                    .addComponent(tfNota1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbEstado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEstado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEstado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEstado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEstado5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbApellido))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCarrera)
                                            .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCiclo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(rbCiclo01)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbCiclo02))))
                                    .addComponent(lbTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(lbApellido)
                            .addComponent(lbCarrera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCiclo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCiclo01)
                            .addComponent(rbCiclo02))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreo)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMateria)
                            .addComponent(lbUv)
                            .addComponent(lbNotas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado1)
                            .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado2)
                            .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado3)
                            .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado4)
                            .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado5)
                            .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        String cicloActual = "";
        String carrera = "";
        String Name = "";
        String Apellido = "";

        //Validacion del ciclo
        if (this.rbCiclo01.isSelected()) {
            cicloActual = "01";
        } else if (this.rbCiclo02.isSelected()) {
            cicloActual = "02";
        } else {
            cicloActual = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione un ciclo",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        String nombre = tfNombre.getText();

        if (nombre.isEmpty()) {
            Name = "-1";
            JOptionPane.showMessageDialog(this, "Ingrese un nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }
        String apellido = tfApellido.getText();

        if (apellido.isEmpty()) {
            Apellido = "-1";
            JOptionPane.showMessageDialog(this, "Ingrese un apellido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

        //Convertir el dato obtenido del selector a String
        String CarreraSeleccionada = (String) cbCarrera.getSelectedItem();

        //Validacion de carrera
        //.equals = es igual a
        if ("Seleccione las carreras".equals(CarreraSeleccionada)) {
            carrera = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione las carreras", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!"-1".equals(cicloActual) && !"-1".equals(carrera) && !"-1".equals(Name)&& !"-1".equals(Apellido)) {
            JOptionPane.showMessageDialog(this, "Registro Exitosos de: "
                    + this.tfNombre.getText() + " " + this.tfApellido.getText() + "\n"
                    + "Estudiante de la carrera " + this.cbCarrera.getSelectedItem()
                    + "\nCon el correo " + this.tfCorreo.getText()
                    + "\nEn el ciclo " + cicloActual);
        }

    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void tfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfCorreoActionPerformed

    private void cbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria3ActionPerformed

    private void cbMateria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria4ActionPerformed

    private void tfCumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCumActionPerformed

    private void rbCiclo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCiclo02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCiclo02ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:

        
        JLabel[] estadoLabels = {lbEstado1, lbEstado2, lbEstado3, lbEstado4, lbEstado5};
        JComboBox[] comboUV = {cbUv1, cbUv2, cbUv3, cbUv4, cbUv5};
        JTextField[] notaFields = {tfNota1, tfNota2, tfNota3, tfNota4, tfNota5};
        double totalNotasUV = 0;
        double totalUV = 0;

        for (int i = 0; i < notaFields.length; i++) {
            double nota = Double.parseDouble(notaFields[i].getText());
            double uv = Double.parseDouble(comboUV[i].getSelectedItem().toString());

            totalNotasUV += nota * uv;
            totalUV += uv;
        }

        if (totalUV == 0) {
            throw new ArithmeticException("No se pueden dividir por cero.");
        }

        double cum = (double) (totalNotasUV / totalUV);

        DecimalFormat formato = new DecimalFormat("#.00");

        String cumFormateado = formato.format(cum);

        tfCum.setText(cumFormateado);
        
        
        for (int i = 0; i < 5; i++) {
            try {
                int nota = Integer.parseInt(notaFields[i].getText());

                if (nota < 0 || nota > 10) {
                    JOptionPane.showMessageDialog(this, "Nota " + (i + 1) + " no válida", "Error", JOptionPane.ERROR_MESSAGE);
                    estadoLabels[i].setText("ESTADO");

                } else {
                    estadoLabels[i].setText(nota > 5 ? "Aprobado" : "Reprobado");

                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Rellene el campo " + (i + 1), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        int materiasAprobadas = 0;
        int materiasReprobadas = 0;

        for (int i = 0; i < 5; i++) {
            int nota = Integer.parseInt(notaFields[i].getText());
            if (nota > 5) {
                materiasAprobadas++;
            } else {
                materiasReprobadas++;
            }
        }

        JComboBox[] Materia = {cbMateria1, cbMateria2, cbMateria3, cbMateria4, cbMateria5};
        String Materias = "";
        String Unidadees = "";
        String Name = "";
        String Apellido = "";

        for (int i = 0; i < Materia.length; i++) {
            if ("Seleccione una opcion".equals(Materia[i].getSelectedItem())) {
                Materias = "-1";
                JOptionPane.showMessageDialog(this, "Seleccione las materias", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        for (int i = 0; i < comboUV.length; i++) {
            if ("0".equals(comboUV[i].getSelectedItem())) {
                Unidadees = "-1";
                JOptionPane.showMessageDialog(this, "Ingrese una Unidad Valorativa Distinta a 0", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        String nombre = tfNombre.getText();

        if (nombre.isEmpty()) {
            Name = "-1";
            JOptionPane.showMessageDialog(this, "Ingrese un nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        String apellido = tfApellido.getText();

        if (apellido.isEmpty()) {
            Apellido = "-1";
            JOptionPane.showMessageDialog(this, "Ingrese un apellido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (!"-1".equals(Materias) && !"-1".equals(Unidadees) && !"-1".equals(Name)&& !"-1".equals(Apellido)) {
            tfDescripcion.setText(nombre +" "+apellido
                    + " su estado actual es de " + materiasAprobadas
                    + " materias aprobadas y " + materiasReprobadas
                    + " materias reprobadas y su CUM es de " + cumFormateado
            );
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void tfNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota1ActionPerformed

    private void cbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUv1;
    private javax.swing.JComboBox<String> cbUv2;
    private javax.swing.JComboBox<String> cbUv3;
    private javax.swing.JComboBox<String> cbUv4;
    private javax.swing.JComboBox<String> cbUv5;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbCum;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNotas;
    private javax.swing.JLabel lbTituloVentana;
    private javax.swing.JLabel lbUv;
    private javax.swing.JRadioButton rbCiclo01;
    private javax.swing.JRadioButton rbCiclo02;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfCum;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables

}
